# Generated by Django 4.1.3 on 2022-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_amount_alter_checkoutaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
