# Generated by Django 4.1.3 on 2022-12-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_checkoutaddress_user_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
    ]
