# Generated by Django 4.1.3 on 2022-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Superb')], default=1),
        ),
    ]
